// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClxA9rTtuFt_S09x_YFxUBLYeyv1X0H8I',
    appId: '1:128382843737:web:036d8e8d1361f7e79c2a48',
    messagingSenderId: '128382843737',
    projectId: 'authexample-43918',
    authDomain: 'authexample-43918.firebaseapp.com',
    storageBucket: 'authexample-43918.firebasestorage.app',
    measurementId: 'G-WHV0MP0J5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArHo49l0NVbN48zAKwoyet2_iRHffzX6g',
    appId: '1:128382843737:android:c8efb36e45ba08809c2a48',
    messagingSenderId: '128382843737',
    projectId: 'authexample-43918',
    storageBucket: 'authexample-43918.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB15pgGClMDRRhnrIxliRs5rQ2Cy_VQWQM',
    appId: '1:128382843737:ios:38a30089df4559719c2a48',
    messagingSenderId: '128382843737',
    projectId: 'authexample-43918',
    storageBucket: 'authexample-43918.firebasestorage.app',
    iosBundleId: 'com.example.noteManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB15pgGClMDRRhnrIxliRs5rQ2Cy_VQWQM',
    appId: '1:128382843737:ios:38a30089df4559719c2a48',
    messagingSenderId: '128382843737',
    projectId: 'authexample-43918',
    storageBucket: 'authexample-43918.firebasestorage.app',
    iosBundleId: 'com.example.noteManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClxA9rTtuFt_S09x_YFxUBLYeyv1X0H8I',
    appId: '1:128382843737:web:d501af924c61203f9c2a48',
    messagingSenderId: '128382843737',
    projectId: 'authexample-43918',
    authDomain: 'authexample-43918.firebaseapp.com',
    storageBucket: 'authexample-43918.firebasestorage.app',
    measurementId: 'G-ME7Y7PJZCV',
  );
}
