// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpyiIK5bLsw6HS6VhgeiLQE-iJesVPAL8',
    appId: '1:926856193056:web:1f097429d4aaf28a6d0845',
    messagingSenderId: '926856193056',
    projectId: 'islami-ebook-store',
    authDomain: 'islami-ebook-store.firebaseapp.com',
    storageBucket: 'islami-ebook-store.firebasestorage.app',
    measurementId: 'G-SLWCJNB81M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPfiEsbRE6_2yOVdlVeeAoqdKCUx85vd8',
    appId: '1:926856193056:android:7fabf60b4b75475a6d0845',
    messagingSenderId: '926856193056',
    projectId: 'islami-ebook-store',
    storageBucket: 'islami-ebook-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpnBN4pMJK3prV3d_kr-jMrYGyyus_cto',
    appId: '1:926856193056:ios:002d3ec687e906ee6d0845',
    messagingSenderId: '926856193056',
    projectId: 'islami-ebook-store',
    storageBucket: 'islami-ebook-store.firebasestorage.app',
    iosBundleId: 'com.example.jamatEIslamiBooksStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpnBN4pMJK3prV3d_kr-jMrYGyyus_cto',
    appId: '1:926856193056:ios:002d3ec687e906ee6d0845',
    messagingSenderId: '926856193056',
    projectId: 'islami-ebook-store',
    storageBucket: 'islami-ebook-store.firebasestorage.app',
    iosBundleId: 'com.example.jamatEIslamiBooksStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpyiIK5bLsw6HS6VhgeiLQE-iJesVPAL8',
    appId: '1:926856193056:web:debbb608506880f36d0845',
    messagingSenderId: '926856193056',
    projectId: 'islami-ebook-store',
    authDomain: 'islami-ebook-store.firebaseapp.com',
    storageBucket: 'islami-ebook-store.firebasestorage.app',
    measurementId: 'G-RLS2L468S2',
  );
}
