import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:jamat_e_islami_books_store/Models/Data.dart';
import 'package:jamat_e_islami_books_store/config/Theme.dart';
import 'package:jamat_e_islami_books_store/controller/BookRepository.dart';
import 'package:jamat_e_islami_books_store/firebase_options.dart';
import 'package:jamat_e_islami_books_store/pages/HomePage/HomePage.dart';
import 'package:jamat_e_islami_books_store/pages/Login%20Page/LoginPage.dart';
import 'package:jamat_e_islami_books_store/pages/SplashScreenPage/SplashScreen.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Initialise Firebase with the per-platform options generated by
  // `flutterfire configure`. Must run before any Firebase service is used.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  // Seed the in-memory book repository with the 16 hardcoded books
  // (their PDFs live on Cloudinary under islami_books/pdfs/...). New
  // books published via AddNewBook are appended on top.
  BookRepository.instance.books.addAll(bookData);
  // Cloudinary uploads use direct HTTPS, no async SDK init needed here.
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Islamic E-Book',
      debugShowCheckedModeBanner: false,
      theme: lightTheme,
      home: const _AuthGate(),
    );
  }
}

/// Watches [FirebaseAuth] for sign-in state changes and routes the app
/// between the splash screen, [LoginScreen], and [Homepage] accordingly.
/// This is the single source of truth for post-auth navigation — every
/// page that triggers a sign-in / sign-out can simply call Firebase and
/// let this widget rebuild the tree.
class _AuthGate extends StatelessWidget {
  const _AuthGate();

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        // While we're waiting for the first auth event keep the splash
        // visible so the app doesn't flash the login screen on cold start.
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const SplashScreen();
        }
        final user = snapshot.data;
        if (user == null) {
          return const LoginScreen();
        }
        return const Homepage();
      },
    );
  }
}
