// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX9a8ox4TtHp1_0COmkwZTEXYVGhSZiqg',
    appId: '1:646168085045:web:9002b5c37d791c26d7a77c',
    messagingSenderId: '646168085045',
    projectId: 'login-logout-taskadd-post',
    authDomain: 'login-logout-taskadd-post.firebaseapp.com',
    storageBucket: 'login-logout-taskadd-post.firebasestorage.app',
    measurementId: 'G-TYPS2X2557',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZjbnZTBibQopta0zFstmuM-QGtW7Sh_A',
    appId: '1:646168085045:android:024a83b4b8f8ab60d7a77c',
    messagingSenderId: '646168085045',
    projectId: 'login-logout-taskadd-post',
    storageBucket: 'login-logout-taskadd-post.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChKYh5DYDfmQYwYso0Pi8e3Sj2J-ZwAXA',
    appId: '1:646168085045:ios:80b6201dc3dbf5a0d7a77c',
    messagingSenderId: '646168085045',
    projectId: 'login-logout-taskadd-post',
    storageBucket: 'login-logout-taskadd-post.firebasestorage.app',
    iosBundleId: 'com.example.loginLogoutTaskaddPost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChKYh5DYDfmQYwYso0Pi8e3Sj2J-ZwAXA',
    appId: '1:646168085045:ios:80b6201dc3dbf5a0d7a77c',
    messagingSenderId: '646168085045',
    projectId: 'login-logout-taskadd-post',
    storageBucket: 'login-logout-taskadd-post.firebasestorage.app',
    iosBundleId: 'com.example.loginLogoutTaskaddPost',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX9a8ox4TtHp1_0COmkwZTEXYVGhSZiqg',
    appId: '1:646168085045:web:ea32ded4d7ed487cd7a77c',
    messagingSenderId: '646168085045',
    projectId: 'login-logout-taskadd-post',
    authDomain: 'login-logout-taskadd-post.firebaseapp.com',
    storageBucket: 'login-logout-taskadd-post.firebasestorage.app',
    measurementId: 'G-8FVFGF8951',
  );
}
